GENERAL:
  DISPLAY_NAME: "Mininion"
MENU:
  minion-menu-name: "&7Minion &4Menu"
APPEARANCE:
  HEAD: "PoXel6"
  CHESTPLATE: DIAMOND_CHESTPLATE
  LEGGINGS: DIAMOND_LEGGINGS
  BOOTS: DIAMOND_BOOTS
TAB_COMPLETIONS:
  - StoneMinion
  - Minion
  - reload