GENERAL:
  DISPLAY_NAME: "Mininion"
APPEARANCE:
  HEAD: "PoXel6"
  CHESTPLATE: DIAMOND_CHESTPLATE
  LEGGINGS: DIAMOND_LEGGINGS
  BOOTS: DIAMOND_BOOTS
TAB_COMPLETIONS:
  - StoneMinion
  - Minion
  - reload